SELECT * 
FROM ARM_CDW.PROGRAM_TRICKS_PERSONALISATION PTP
WHERE PTP.SHORTPROGRAMTITLE LIKE '%TONIGHT SHOW%'
AND TO_CHAR(PROGRAMSTARTLOCAL, 'YYYYMMDD') >= 20130215
AND TO_CHAR(PROGRAMSTARTLOCAL, 'YYYYMMDD') <= 20140215
ORDER BY PROGRAMSTARTLOCAL ASC;
